NCMF\UserBundle\Entity\UserInfo:
    type: mappedSuperclass
    table: null
    repositoryClass: NCMF\UserBundle\Repository\UserInfoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: true
        secondName:
            type: string
            length: 255
            column: second_name
            nullable: true
        lastName:
            type: string
            length: 255
            column: last_name
            nullable: true
        company:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        taxNumber:
            type: bigint
            unique: true
            column: tax_number
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        discount:
            type: smallint
            nullable: true
    oneToOne:
        user:
            targetEntity: User
            joinColumn:
                nullable: false
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
