fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: NCMF\UserBundle\Entity\User
    from_email:
        address: "robot@example.com"
        sender_name: "Robot"