imports:
    - { resource: "@NCMFUserBundle/Resources/config/services.yml" }
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    service:
        mailer: fos_user.mailer.twig_swift
    user_class: NCMF\UserBundle\Entity\User
    from_email:
        address: "robot@example.com"
        sender_name: "Robot"
    registration:
        form:
            type: NCMF\UserBundle\Form\Type\RegistrationFormType
        confirmation:
            enabled: true
framework:
    translator: { fallbacks: ['%locale%'] }