services:
    app.form.registration:
        class: NCMF\UserBundle\Form\Type\RegistrationFormType
        arguments: ['@doctrine.orm.entity_manager', '%secret%']
        tags:
            - { name: form.type, alias: app_user_registration }