#NCMF\UserBundle\Entity\User:
#    constraints:
#        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
#            fields: [username_canonical]
#            groups: [Registration, Profile]
#            errorPath: username_canonical
#            message: 'Имя пользователя уже используется'